disabled_rules:
 - trailing_comma
 - trailing_whitespace
 - force_cast

opt_in_rules:
  - file_length
  - function_body_length
  - line_length
  - todo
  - type_body_length
  - variable_name
  - type_name
  - function_parameter_count

line_length:
  error: 600
  warning: 400

file_length:
  warning: 900
  error: 1200

large_tuple:
  warning: 3
  error: 4

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods