language: objective-c
osx_image: xcode8.3
sudo: false

before_script:
    - brew update && brew upgrade xctool

script:
    - xctool -workspace FlickrClient.xcworkspace -scheme FlickrClient -sdk iphonesimulator clean build test

branches:
  only:
    - master
