platform :ios, ’10.0’
use_frameworks!

target "FlickrClient" do
    pod 'SDWebImage', '~>3.8'
    pod 'ReachabilitySwift', '~> 3'
    pod 'SwiftLint'
    pod 'SwiftyJSON'
end

target "FlickrKit" do
    pod 'SwiftyJSON'
    target "FlickrKitTests" do
        inherit! :search_paths
    end
end
